
package ru.rrozhkov.easykin.android.ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EasyKinService", targetNamespace = "http://rrozhkov.ru/easykin")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EasyKinService {


    /**
     * 
     * @return
     *     returns java.util.List<ru.rrozhkov.easykin.android.ws.client.CategoryBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "categories", targetNamespace = "http://rrozhkov.ru/easykin", className = "ru.rrozhkov.easykin.android.ws.client.Categories")
    @ResponseWrapper(localName = "categoriesResponse", targetNamespace = "http://rrozhkov.ru/easykin", className = "ru.rrozhkov.easykin.android.ws.client.CategoriesResponse")
    public List<CategoryBean> categories();

    /**
     * 
     * @return
     *     returns java.util.List<ru.rrozhkov.easykin.android.ws.client.PersonBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "persons", targetNamespace = "http://rrozhkov.ru/easykin", className = "ru.rrozhkov.easykin.android.ws.client.Persons")
    @ResponseWrapper(localName = "personsResponse", targetNamespace = "http://rrozhkov.ru/easykin", className = "ru.rrozhkov.easykin.android.ws.client.PersonsResponse")
    public List<PersonBean> persons();

    /**
     * 
     * @return
     *     returns java.util.List<ru.rrozhkov.easykin.android.ws.client.TaskBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tasks", targetNamespace = "http://rrozhkov.ru/easykin", className = "ru.rrozhkov.easykin.android.ws.client.Tasks")
    @ResponseWrapper(localName = "tasksResponse", targetNamespace = "http://rrozhkov.ru/easykin", className = "ru.rrozhkov.easykin.android.ws.client.TasksResponse")
    public List<TaskBean> tasks();

}
