
package ru.rrozhkov.easykin.android.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EasyKin", targetNamespace = "http://rrozhkov.ru/easykin", wsdlLocation = "http://localhost:8081/EasyKinService/?wsdl")
public class EasyKin
    extends Service
{

    private final static URL EASYKIN_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.rrozhkov.easykin.android.ws.client.EasyKin.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.rrozhkov.easykin.android.ws.client.EasyKin.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/EasyKinService/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/EasyKinService/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EASYKIN_WSDL_LOCATION = url;
    }

    public EasyKin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EasyKin() {
        super(EASYKIN_WSDL_LOCATION, new QName("http://rrozhkov.ru/easykin", "EasyKin"));
    }

    /**
     * 
     * @return
     *     returns EasyKinService
     */
    @WebEndpoint(name = "EasyKinPort")
    public EasyKinService getEasyKinPort() {
        return super.getPort(new QName("http://rrozhkov.ru/easykin", "EasyKinPort"), EasyKinService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EasyKinService
     */
    @WebEndpoint(name = "EasyKinPort")
    public EasyKinService getEasyKinPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rrozhkov.ru/easykin", "EasyKinPort"), EasyKinService.class, features);
    }

}
